spring.application.name=ms-produtos
<<<<<<< HEAD

spring.datasource.url=jdbc:mysql://localhost:3306/feira
spring.datasource.username=feira
spring.datasource.password=feira123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
=======
>>>>>>> 75ba6a85ae3ded2b9d0b2c7b31caba5abbadf6f5
